version: 2
jobs:
  build:
    working_directory: /go/src/github.com/yfuruyama/spanner-cli
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download
      - run: go vet ./...
      - run: make test
